import httpx
import re

from core.logger import get_logger

logger = get_logger(__name__)

INQUIRY_URL = "http://34.87.68.224:8100/api/v1/recommendation/inquiry/whatsapp"
BOOKING_URL = "http://34.87.68.224:8100/api/v1/recommendation/inquiry/book/{ticket_id}/{venue_id}"

async def chat_inquiry(user_name: str, message: str, phone_number: str, k_venue: int = 3) -> str:
    """
    Send a WhatsApp inquiry to the recommendation API and return a formatted response.

    Args:
        user_name (str): The user's name
        message (str): The user's inquiry message
        phone_number (str): The user's phone number
        k_venue (int, optional): Number of venues to recommend (default 3)

    Returns:
        str: Formatted recommendation message
    """
    payload = {
        "phone_number": phone_number,
        "text_body": message,
        "k_venue": k_venue
    }

    async with httpx.AsyncClient(timeout=15) as client:
        response = await client.post(INQUIRY_URL, json=payload)
        # response.raise_for_status()
        
    if response.status_code != 200:
        return "Failed to request inquiry. Please try again later."
    
    data = response.json()

    ticket_id = data.get("ticket_id", "N/A")
    venues = data.get("top_k_venues", [])
    if not venues:
        return f"Ticket ID: {ticket_id}\nHi {user_name}, sorry! I couldn't find any venues matching your request."

    formatted_venues = []
    for idx, venue in enumerate(venues, start=1):
        payload = venue.get("payload", {})
        formatted_venues.append(
            f"{idx}. {payload.get('name')} ({payload.get('id', 'N/A')})\n"
            f"   📍 Location: {payload.get('location', 'N/A')}\n"
            f"   🏷️ Type: {payload.get('type', 'N/A')}\n"
            f"   ⭐ Amenities: {payload.get('amenities', 'N/A')}\n"
            f"   📞 Contact: {payload.get('contact_name', 'N/A')} ({payload.get('contact_numb', 'N/A')})\n"
        )

    response_text = (
        f"🎟️ Ticket ID: {ticket_id}\n\n"
        f"Hi {user_name}, Welcome to Venuexplorer! Based on your request, here are the top {len(formatted_venues)} venue recommendations:\n\n"
        + "\n".join(formatted_venues)
        + "\nTo book a venue, please reply with: book #  (for example: book 1)"
    )

    return response_text

async def book_selected_venue(selected_venue_index: int, inquiry_chat: str) -> str:
    """
    Parse inquiry_chat, extract ticket_id and venue info for the selected venue,
    then call the booking API. Returns a user-friendly confirmation message.

    Args:
        selected_venue_index (int): The number of the venue chosen (1-based index).
        inquiry_chat (str): The full chat response generated by chat_response.

    Returns:
        str: Confirmation message for the user.
    """
    # 1. Extract ticket_id
    ticket_match = re.search(r"Ticket ID:\s*([A-Z0-9\-]+)", inquiry_chat)
    if not ticket_match:
        return "Sorry, I could not find a ticket ID in your inquiry."

    ticket_id = ticket_match.group(1)

    # 2. Extract all venues
    venue_pattern = re.compile(
        r"(\d+)\.\s+(.*?)\s+\((\d+)\)\n"
        r"\s+📍 Location:\s*(.*?)\n"
        r"\s+🏷️ Type:\s*(.*?)\n"
        r"\s+⭐ Amenities:\s*(.*?)\n"
        r"\s+📞 Contact:\s*(.*?)\s+\((.*?)\)",
        re.DOTALL,
    )
    venues = venue_pattern.findall(inquiry_chat)

    if not venues or selected_venue_index < 1 or selected_venue_index > len(venues):
        return "❌ Invalid venue selection. Please try again."

    # 3. Get selected venue
    _, name, venue_id, _, _, _, _, _ = venues[selected_venue_index - 1]

    # 4. Hit booking API
    booking_url = BOOKING_URL.format(ticket_id=ticket_id, venue_id=venue_id)
    async with httpx.AsyncClient(timeout=15) as client:
        response = await client.get(booking_url)

    if response.status_code == 200:
        return f"Success! The venue *{name.strip()}* ({venue_id}) has been successfully booked under ticket {ticket_id}."
    else:
        return f"Failed to book the venue *{name.strip()}* ({venue_id}). Please try again later."